9317
training ....
  0%|                                                                                                                                                                                                     | 0/10 [00:00<?, ?it/s]

/home/hardk/.local/lib/python3.10/site-packages/transformers/generation/utils.py:1186: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
  0%|                                                                                                                                                                                                     | 0/10 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/hardk/AMNESIA/College/Sem 4/NLP/Project/Jainit Repo/Styled_ChatBot/Final Model/main.py", line 179, in <module>
    train(chatData, model, optim, int(NUM_EPOCHS))
  File "/home/hardk/AMNESIA/College/Sem 4/NLP/Project/Jainit Repo/Styled_ChatBot/Final Model/main.py", line 87, in train
    wandb.log({"loss": loss, "epoch": i, "learning_rate": optim.param_groups[0]['lr'],"data": {"Hello, how are you?": {"ans1":ans_ques1},
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 344, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1750, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1531, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1401, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 579, in publish_partial_history
    item.value_json = json_dumps_safer_history(v)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/util.py", line 827, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/util.py", line 792, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
Traceback (most recent call last):
  File "/home/hardk/AMNESIA/College/Sem 4/NLP/Project/Jainit Repo/Styled_ChatBot/Final Model/main.py", line 179, in <module>
    train(chatData, model, optim, int(NUM_EPOCHS))
  File "/home/hardk/AMNESIA/College/Sem 4/NLP/Project/Jainit Repo/Styled_ChatBot/Final Model/main.py", line 87, in train
    wandb.log({"loss": loss, "epoch": i, "learning_rate": optim.param_groups[0]['lr'],"data": {"Hello, how are you?": {"ans1":ans_ques1},
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 344, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1750, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1531, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1401, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 579, in publish_partial_history
    item.value_json = json_dumps_safer_history(v)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/util.py", line 827, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/hardk/.local/lib/python3.10/site-packages/wandb/util.py", line 792, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable